import type { DemoMeetingTopic } from "../lib/demoMeetingCatalog";
import { DemoDomainVisuals } from "./DemoDomainVisuals";
export type DemoMetricSelection={topicId:string;title:string;value:string;note:string;basis:string};
type Props={topic:DemoMeetingTopic;onMetricSelect?:(metric:DemoMetricSelection)=>void}; type Lens={title:string;value:string;note:string;kind:string;basis:string};
const KpiIcon=({kind}:{kind:string})=>{const paths:Record<string,React.ReactNode>={income:<><path d="M5 18V12M12 18V8M19 18V4"/><path d="M3 21h18"/></>,loss:<><path d="M12 3 2.8 20h18.4L12 3Z"/><path d="M12 9v4M12 17h.01"/></>,cash:<><ellipse cx="12" cy="6" rx="7" ry="3"/><path d="M5 6v6c0 1.7 3.1 3 7 3s7-1.3 7-3V6M5 12v6c0 1.7 3.1 3 7 3s7-1.3 7-3v-6"/></>,process:<><circle cx="12" cy="12" r="8"/><path d="M12 7v5l3 2"/></>,risk:<><path d="M12 3 4 6v5c0 5 3.4 8.5 8 10 4.6-1.5 8-5 8-10V6l-8-3Z"/><path d="M9 12l2 2 4-5"/></>};return <span className={`kpi-icon ${kind}`}><svg viewBox="0 0 24 24" aria-hidden="true">{paths[kind]||paths.process}</svg></span>};
const lenses:Record<string,Lens[]>={
 facturacion:[{title:"Crecimiento potencial",value:"+$185 M",note:"Servicios/capacidad/demanda",kind:"income",basis:"Estimación demo: brecha capacidad-demanda y portafolio"},{title:"Fugas evitables",value:"$96 M",note:"Producción no capturada/retrasos",kind:"loss",basis:"Estimación demo: devoluciones + retrasos + no facturado"},{title:"Cartera priorizable",value:"$742 M",note:">90 días · recuperación",kind:"cash",basis:"Saldo demo segmentado por edad y pagador"},{title:"Ciclo factura-radicación",value:"18,7 d",note:"Meta demo 9 días",kind:"process",basis:"Promedio demo fecha factura-radicación"}],
 glosas:[{title:"Valor glosado",value:"$624 M",note:"Pareto por valor",kind:"loss",basis:"Glosas demo acumuladas"},{title:"Recuperable potencial",value:"$286 M",note:"Causales/pagadores",kind:"income",basis:"Estimación demo según causal y antecedente"},{title:"Frecuencia",value:"7,4%",note:"Pareto causal/servicio",kind:"process",basis:"Facturas demo con glosa / auditadas"},{title:"Devoluciones",value:"Top 5",note:"Motivos recurrentes",kind:"risk",basis:"Ranking demo por frecuencia"}],
 rrhh:[{title:"Productividad",value:"+12%",note:"Capacidad/carga",kind:"income",basis:"Escenario demo de redistribución"},{title:"Ausentismo",value:"6,8%",note:"Áreas/turnos",kind:"loss",basis:"Novedades demo / tiempo programado"},{title:"Horas extra",value:"$74 M",note:"Costo mensual",kind:"cash",basis:"Horas demo × costo laboral"},{title:"Automatización",value:"6 frentes",note:"Trabajo repetitivo",kind:"process",basis:"Procesos demo repetitivos detectados"}], operaciones:[{title:"Reprocesos",value:"11%",note:"Errores/retornos",kind:"loss",basis:"Casos demo que regresan de etapa"},{title:"Tiempo de ciclo",value:"52 min",note:"Espera/transferencia",kind:"process",basis:"Tiempos demo extremo a extremo"},{title:"Cuellos de botella",value:"4",note:"Dependencias críticas",kind:"risk",basis:"Etapas demo con cola/dependencia"},{title:"Capacidad",value:"73%",note:"Uso/oportunidad",kind:"income",basis:"Volumen demo / capacidad disponible"}],
 compras:[{title:"Ahorro potencial",value:"$118 M",note:"Precio/negociación",kind:"income",basis:"Brecha demo precio/consumo"},{title:"Inventario en riesgo",value:"$96 M",note:"Rotación/vencimiento",kind:"loss",basis:"Stock demo lento/próximo a vencer"},{title:"Compras urgentes",value:"8,7%",note:"Sobrecosto",kind:"cash",basis:"Órdenes demo urgentes / total"},{title:"Dependencia",value:"3 prov.",note:"Concentración",kind:"risk",basis:"Participación demo por proveedor"}],
 sistemas:[{title:"Riesgos críticos",value:"5",note:"Ciber/continuidad",kind:"risk",basis:"Matriz demo probabilidad-impacto"},{title:"Procesos manuales",value:"126 h",note:"Redigitación/mes",kind:"loss",basis:"Frecuencia demo × tiempo manual"},{title:"Integraciones",value:"9",note:"Interfaces manuales",kind:"process",basis:"Mapa demo de aplicaciones/flujos"},{title:"Aplicaciones",value:"14",note:"Dependencias",kind:"cash",basis:"Inventario tecnológico demo"}]};
const stories:Record<string,string[]>={facturacion:["Portafolio actual vs demanda/mercado","Capacidad instalada vs producción facturable","Fugas desde prestación hasta recaudo","Cartera por pagador, edad y recuperabilidad"],glosas:["Pareto glosas por frecuencia","Pareto glosas por valor","Causales más recurrentes por servicio","Entidades/pagadores con mayor glosa","Servicios y tarifas más impactados","Oportunidades de recuperación y gestión"],rrhh:["Productividad/carga por rol","Ausentismo/rotación","Horas extra/capacidad","Automatización/redistribución"],operaciones:["Flujo extremo a extremo","Tiempo/espera/reproceso por etapa","Errores/retornos entre áreas","Cuellos y dependencias"],compras:["Precio por proveedor","Rotación/faltantes/vencimientos","Compras urgentes/sobrecostos","Concentración/negociación"],sistemas:["Mapa de riesgos informáticos","Criticidad/continuidad","Integraciones/puntos manuales","Dependencias/duplicidad"]};
export function DemoExecutiveIntelligence({topic,onMetricSelect}:Props){const ls=lenses[topic.id]||[],ss=stories[topic.id]||[];return <section className="demo-intelligence"><header><div><span className="presentacion-chart-kicker">INTELIGENCIA EJECUTIVA EIIAX</span><h2>{topic.label}</h2></div><span className="badge demo-badge">SIMULACIÓN</span></header><div className="demo-intel-kpis">{ls.map(x=><article className={`demo-intel-kpi ${x.kind}`} key={x.title} title={`${x.basis} · Doble clic: detalle privado`} onDoubleClick={()=>onMetricSelect?.({topicId:topic.id,title:x.title,value:x.value,note:x.note,basis:x.basis})}><KpiIcon kind={x.kind}/><div className="kpi-copy"><small>{x.title} <i className="kpi-info" title={x.basis}>i</i></small><strong>{x.value}</strong><span>{x.note}</span><em>Base: {x.basis}</em></div></article>)}</div>
<DemoDomainVisuals topic={topic} onMetricSelect={(title,value,note,basis)=>onMetricSelect?.({topicId:topic.id,title,value,note,basis})}/><div className="demo-intel-context"><div className="demo-intel-story"><h3>Qué investigaría EIIAX <span className="dv-help" title="Esta lista es una muestra del alcance para la demostración. En una evaluación real EIIAX amplía el análisis según los datos, procesos, hallazgos y preguntas de la organización.">?</span></h3>{ss.map((x,i)=><div key={x}><b>{i+1}</b><span>{x}</span></div>)}</div><div className="demo-intel-priority"><h3>Decisión gerencial</h3><strong>{topic.oportunidades[0]}</strong><p>{topic.oportunidades[1]||"Priorizar por impacto, factibilidad y evidencia."}</p><div className="priority-tags"><span>Impacto económico</span><span>Factibilidad</span><span>Urgencia</span></div></div></div>
<div className="demo-opportunity-rank"><h3>Oportunidades priorizadas</h3>{topic.oportunidades.slice(0,4).map((x,i)=><article key={x}><b>#{i+1}</b><span>{x}</span><small>{i===0?"ALTO IMPACTO":i===1?"IMPACTO MEDIO-ALTO":"VALIDAR CON DATOS"}</small></article>)}</div><footer><b>EIIAX no se limita a estos indicadores.</b> Cruza áreas, investiga causas y prioriza oportunidades de mayores ingresos, menores pérdidas, costos y riesgos. Las cifras mostradas son simuladas/estimadas.</footer></section>}
