import { useState } from "react";
type PrivateKey="ingresos"|"glosas"|"manual"|"respuesta";
const PRIVATE:Record<PrivateKey,{title:string,steps:string[],answer:string}>={
ingresos:{title:"+$185 M · nuevos ingresos",steps:["Cruzar servicios actuales con capacidad instalada y demanda no atendida.","Identificar servicios habilitados subutilizados y oportunidades de contratación.","Estimar volumen incremental × tarifa/margen esperado.","Priorizar oportunidades por factibilidad, inversión y tiempo de captura."],answer:"EIIAX identifica capacidad y demanda aprovechable, cuantifica oportunidades y prioriza las de mayor valor y factibilidad. La cifra final se recalcula con información real de la IPS."},
glosas:{title:"$286 M · recuperación / pérdida evitable",steps:["Segmentar cartera y glosa por pagador, edad, causal y valor.","Clasificar recuperable, conciliable, subsanable y baja probabilidad.","Priorizar valor × probabilidad × vencimiento.","Asignar acciones, responsables y fecha de gestión.","Medir recuperado real contra línea base y meta."],answer:"EIIAX identifica dónde está el valor, prioriza casos por probabilidad e impacto y propone la intervención. El resultado depende también de información, gestión e implementación de la IPS."},
manual:{title:"200 h/mes · capacidad liberable",steps:["Medir tiempos y frecuencia de tareas manuales/repetitivas.","Separar reproceso, espera, redigitación y actividad necesaria.","Seleccionar automatización, integración o rediseño de proceso.","Valorar horas liberadas con costo laboral y uso alternativo.","Medir capacidad realmente reutilizada después de intervenir."],answer:"No se plantea simplemente eliminar horas: EIIAX busca liberar capacidad y mostrar en qué actividad de mayor valor puede reutilizarse, además de cuantificar el ahorro cuando corresponda."},
respuesta:{title:"9 días · reducción del ciclo",steps:["Descomponer el ciclo por etapa, responsable y tiempo de espera.","Localizar cuellos de botella y dependencias.","Estandarizar reglas, alertas y asignación de casos.","Priorizar por vencimiento, valor y criticidad.","Comparar tiempo real posterior contra línea base."],answer:"EIIAX reduce esperas atacando etapas y dependencias concretas; la meta se valida con los tiempos reales y los compromisos operativos de la IPS."}}
const Metric=({id,title,actual,meta,delta,money,detail,onPrivate}:{id:PrivateKey,title:string,actual:string,meta:string,delta:string,money:string,detail:string,onPrivate:(id:PrivateKey)=>void})=><article className="close-metric" onDoubleClick={()=>onPrivate(id)} title="Doble clic: estrategia privada del presentador"><div className="close-metric-head"><div><small>{title}</small><strong>{money}</strong></div><span>{delta}</span></div><div className="close-compare"><div><small>HOY</small><b>{actual}</b></div><i>→</i><div className="target"><small>CON EIIAX · META</small><b>{meta}</b></div></div><div className="close-track"><i/></div><p>{detail}</p></article>;
export function DemoExecutiveClose({onPublishCommitments,canPublish=false}:{onPublishCommitments?:()=>void,canPublish?:boolean}){const[privateKey,setPrivateKey]=useState<PrivateKey|null>(null);const info=privateKey?PRIVATE[privateKey]:null;return <div className="executive-close-v2">
<header className="close-hero"><div><span className="semantic-badge hecho">SIMULACIÓN GERENCIAL</span><h3>¿Qué podría cambiar después de intervenir?</h3><p>Escenario ilustrativo: línea base → intervención EIIAX → meta conservadora → medición real.</p></div><div className="close-hero-value"><small>Escenarios de valor · no sumar como un único beneficio certificado</small><strong>$185 M + $286 M</strong><span>nuevo ingreso potencial + recuperación potencial · categorías distintas y sujetas a validación</span></div></header>
<div className="close-kpis"><Metric id="ingresos" onPrivate={setPrivateKey} title="Ingresos adicionales" actual="$0" meta="+$185 M" delta="NUEVO INGRESO" money="+$185 M" detail="Capacidad disponible + demanda + contratación."/><Metric id="glosas" onPrivate={setPrivateKey} title="Pérdidas / glosas" actual="$624 M" meta="$338 M" delta="-45,8%" money="$286 M recuperables" detail="Menor fuga y mayor recuperación potencial."/><Metric id="manual" onPrivate={setPrivateKey} title="Trabajo manual" actual="320 h/mes" meta="120 h/mes" delta="-62,5%" money="200 h/mes liberadas" detail="Capacidad reutilizable en análisis, seguimiento y servicio."/><Metric id="respuesta" onPrivate={setPrivateKey} title="Respuesta a glosas" actual="16 días" meta="7 días" delta="-56,3%" money="9 días menos" detail="Menor ciclo y recuperación más oportuna."/></div>
<section className="close-value-use"><h3>¿Dónde se materializa el valor?</h3><div><span><b>+$185 M</b> potencial de nuevos ingresos</span><span><b>$286 M</b> recuperación / pérdida evitable</span><span><b>200 h/mes</b> capacidad liberada</span><span><b>9 días</b> reducción del ciclo</span></div></section>
<section className="close-roadmap"><h3>Compromisos para convertir la simulación en resultado medible</h3><div className="roadmap-steps"><article><b>1</b><strong>IPS entrega datos</strong><span>Fuentes y períodos acordados</span></article><i>→</i><article><b>2</b><strong>IPS implementa ajustes</strong><span>Responsable y recursos disponibles</span></article><i>→</i><article><b>3</b><strong>EIIAX valida y acompaña</strong><span>Línea base, acciones y metas</span></article><i>→</i><article><b>4</b><strong>Ambos miden resultado</strong><span>Real vs. meta + evidencia</span></article></div></section>
<section className="manager-commitments"><div><h3>Compromisos de la IPS / Gerencia</h3><span>Condiciones necesarias para materializar los beneficios; visibles en la Sala del gerente.</span></div><div className="commit-grid"><article><b>Información</b><span>Entregar datos completos por el medio y periodicidad acordados.</span><em>Pendiente</em></article><article><b>Responsable</b><span>Designar funcionario líder y suplente para ejecución y seguimiento.</span><em>Pendiente</em></article><article><b>Implementación</b><span>Garantizar aplicación de los ajustes de proceso aprobados.</span><em>Pendiente</em></article><article><b>Seguimiento</b><span>Participar en validaciones, decisiones y medición de resultados.</span><em>Pendiente</em></article></div>{onPublishCommitments&&<button type="button" className="btn small primary commitment-publish" disabled={!canPublish} onClick={onPublishCommitments}>{canPublish?"Publicar compromisos al gerente":"Abra la Sala para publicar"}</button>}</section>
{info&&<aside className="presenter-private"><div className="private-head"><div><span>PRIVADO · SOLO PRESENTADOR</span><h3>{info.title}</h3></div><button type="button" onClick={()=>setPrivateKey(null)}>×</button></div><div className="private-grid"><section><h4>Cómo se materializaría</h4><ol>{info.steps.map(x=><li key={x}>{x}</li>)}</ol></section><section><h4>Respuesta sugerida al gerente</h4><p>{info.answer}</p><h4>Soporte privado</h4><p>Origen, fórmula, registros y supuestos se sustentan en Detalle y trazabilidad. La metodología y priorización interna no se publican salvo decisión del presentador.</p></section></div></aside>}
<p className="close-disclaimer">DEMO: valores simulados. En evaluación real, línea base, metas, ahorro/ingreso y resultados se recalculan exclusivamente con datos suministrados o conectados por la empresa y supuestos trazables.</p></div>}
