"""orchestration_work_plans_tasks

Revision ID: 4355c73adcb8
Revises: 
Create Date: 2026-08-22 17:58:00.916285

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4355c73adcb8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ai_employees',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('specialty', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('model_provider', sa.String(length=80), nullable=True),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('capabilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capabilities_code'), 'capabilities', ['code'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=40), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('employee_capabilities',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('capability_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['ai_employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tools',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('capability_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('executor_type', sa.String(length=30), nullable=False),
    sa.Column('risk_level', sa.String(length=20), nullable=False),
    sa.Column('requires_approval', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tools_code'), 'tools', ['code'], unique=False)
    op.create_table('work_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('request', sa.Text(), nullable=False),
    sa.Column('objective', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('capability_id', sa.String(length=36), nullable=True),
    sa.Column('employee_id', sa.String(length=36), nullable=True),
    sa.Column('tool_id', sa.String(length=36), nullable=True),
    sa.Column('steps_json', sa.Text(), nullable=True),
    sa.Column('dependencies_json', sa.Text(), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('approval_status', sa.String(length=30), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['ai_employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_plans_correlation_id'), 'work_plans', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_work_plans_created_at'), 'work_plans', ['created_at'], unique=False)
    op.create_index(op.f('ix_work_plans_organization_id'), 'work_plans', ['organization_id'], unique=False)
    op.create_index(op.f('ix_work_plans_status'), 'work_plans', ['status'], unique=False)
    op.create_table('employee_tasks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('work_plan_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=True),
    sa.Column('capability_id', sa.String(length=36), nullable=True),
    sa.Column('tool_id', sa.String(length=36), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('executor_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('inputs_json', sa.Text(), nullable=True),
    sa.Column('outputs_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('approval_status', sa.String(length=30), nullable=False),
    sa.Column('cost_reference_json', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['capability_id'], ['capabilities.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['ai_employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.ForeignKeyConstraint(['work_plan_id'], ['work_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_tasks_organization_id'), 'employee_tasks', ['organization_id'], unique=False)
    op.create_index(op.f('ix_employee_tasks_status'), 'employee_tasks', ['status'], unique=False)
    op.create_index(op.f('ix_employee_tasks_work_plan_id'), 'employee_tasks', ['work_plan_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('work_plan_id', sa.String(length=36), nullable=False),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=200), nullable=False),
    sa.Column('employee_name', sa.String(length=200), nullable=True),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('evidence_json', sa.Text(), nullable=True),
    sa.Column('impact', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('requested_by', sa.String(length=36), nullable=False),
    sa.Column('decided_by', sa.String(length=36), nullable=True),
    sa.Column('decision_comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['requested_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['employee_tasks.id'], ),
    sa.ForeignKeyConstraint(['work_plan_id'], ['work_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_organization_id'), 'approval_requests', ['organization_id'], unique=False)
    op.create_index(op.f('ix_approval_requests_status'), 'approval_requests', ['status'], unique=False)
    op.create_index(op.f('ix_approval_requests_work_plan_id'), 'approval_requests', ['work_plan_id'], unique=False)
    op.create_table('finops_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('work_plan_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('model_name', sa.String(length=120), nullable=True),
    sa.Column('provider', sa.String(length=80), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['employee_tasks.id'], ),
    sa.ForeignKeyConstraint(['work_plan_id'], ['work_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('work_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('work_plan_id', sa.String(length=36), nullable=True),
    sa.Column('task_id', sa.String(length=36), nullable=True),
    sa.Column('event_type', sa.String(length=60), nullable=False),
    sa.Column('payload_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['employee_tasks.id'], ),
    sa.ForeignKeyConstraint(['work_plan_id'], ['work_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_events_created_at'), 'work_events', ['created_at'], unique=False)
    op.create_index(op.f('ix_work_events_event_type'), 'work_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_work_events_organization_id'), 'work_events', ['organization_id'], unique=False)
    op.create_index(op.f('ix_work_events_work_plan_id'), 'work_events', ['work_plan_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_events_work_plan_id'), table_name='work_events')
    op.drop_index(op.f('ix_work_events_organization_id'), table_name='work_events')
    op.drop_index(op.f('ix_work_events_event_type'), table_name='work_events')
    op.drop_index(op.f('ix_work_events_created_at'), table_name='work_events')
    op.drop_table('work_events')
    op.drop_table('finops_records')
    op.drop_index(op.f('ix_approval_requests_work_plan_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_status'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_organization_id'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_employee_tasks_work_plan_id'), table_name='employee_tasks')
    op.drop_index(op.f('ix_employee_tasks_status'), table_name='employee_tasks')
    op.drop_index(op.f('ix_employee_tasks_organization_id'), table_name='employee_tasks')
    op.drop_table('employee_tasks')
    op.drop_index(op.f('ix_work_plans_status'), table_name='work_plans')
    op.drop_index(op.f('ix_work_plans_organization_id'), table_name='work_plans')
    op.drop_index(op.f('ix_work_plans_created_at'), table_name='work_plans')
    op.drop_index(op.f('ix_work_plans_correlation_id'), table_name='work_plans')
    op.drop_table('work_plans')
    op.drop_index(op.f('ix_tools_code'), table_name='tools')
    op.drop_table('tools')
    op.drop_table('employee_capabilities')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_capabilities_code'), table_name='capabilities')
    op.drop_table('capabilities')
    op.drop_table('ai_employees')
    op.drop_table('organizations')
    # ### end Alembic commands ###
