"""agent_factory_802

Revision ID: 5b2eb2437398
Revises: 4355c73adcb8
Create Date: 2026-08-22 19:15:52.745770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b2eb2437398'
down_revision: Union[str, Sequence[str], None] = '4355c73adcb8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=True),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('specialty', sa.String(length=120), nullable=False),
    sa.Column('template_json', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_templates_code'), 'employee_templates', ['code'], unique=True)
    op.create_table('employee_certifications',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('result', sa.String(length=30), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('certified_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['certified_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['ai_employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_certifications_employee_id'), 'employee_certifications', ['employee_id'], unique=False)
    op.create_table('employee_instructions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('system_purpose', sa.Text(), nullable=True),
    sa.Column('role_text', sa.Text(), nullable=True),
    sa.Column('objective_text', sa.Text(), nullable=True),
    sa.Column('operating_rules', sa.Text(), nullable=True),
    sa.Column('constraints_text', sa.Text(), nullable=True),
    sa.Column('output_contract', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['ai_employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('employee_knowledge_sources',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('organization_id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('source_type', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('config_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['ai_employees.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_knowledge_sources_employee_id'), 'employee_knowledge_sources', ['employee_id'], unique=False)
    op.create_table('employee_limits',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('max_concurrent_tasks', sa.Integer(), nullable=False),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('max_retries', sa.Integer(), nullable=False),
    sa.Column('daily_cost_limit', sa.Float(), nullable=True),
    sa.Column('task_cost_limit', sa.Float(), nullable=True),
    sa.Column('allowed_hours_json', sa.Text(), nullable=True),
    sa.Column('data_classification', sa.String(length=40), nullable=True),
    sa.Column('approval_threshold', sa.Float(), nullable=True),
    sa.Column('limits_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['ai_employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('employee_model_policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('preferred_provider', sa.String(length=80), nullable=True),
    sa.Column('preferred_model', sa.String(length=120), nullable=True),
    sa.Column('allowed_models_json', sa.Text(), nullable=True),
    sa.Column('fallback_model', sa.String(length=120), nullable=True),
    sa.Column('max_tokens', sa.Integer(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=True),
    sa.Column('budget_daily', sa.Float(), nullable=True),
    sa.Column('cost_ceiling', sa.Float(), nullable=True),
    sa.Column('policy_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['ai_employees.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_table('employee_test_cases',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('test_type', sa.String(length=30), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=False),
    sa.Column('expected_json', sa.Text(), nullable=True),
    sa.Column('validation_rules_json', sa.Text(), nullable=True),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['ai_employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_test_cases_employee_id'), 'employee_test_cases', ['employee_id'], unique=False)
    op.create_table('employee_tool_grants',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('tool_id', sa.String(length=36), nullable=False),
    sa.Column('permission', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['ai_employees.id'], ),
    sa.ForeignKeyConstraint(['tool_id'], ['tools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_tool_grants_employee_id'), 'employee_tool_grants', ['employee_id'], unique=False)
    op.create_table('employee_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('configuration_json', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['ai_employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_versions_employee_id'), 'employee_versions', ['employee_id'], unique=False)
    op.create_table('employee_test_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('employee_id', sa.String(length=36), nullable=False),
    sa.Column('test_case_id', sa.String(length=36), nullable=True),
    sa.Column('test_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=True),
    sa.Column('actual_json', sa.Text(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('tools_used_json', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['ai_employees.id'], ),
    sa.ForeignKeyConstraint(['test_case_id'], ['employee_test_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_test_runs_employee_id'), 'employee_test_runs', ['employee_id'], unique=False)
    op.add_column('ai_employees', sa.Column('code', sa.String(length=80), nullable=True))
    op.add_column('ai_employees', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('ai_employees', sa.Column('role', sa.String(length=120), nullable=True))
    op.add_column('ai_employees', sa.Column('objective', sa.Text(), nullable=True))
    op.add_column('ai_employees', sa.Column('lifecycle_status', sa.String(length=40), nullable=True))
    op.add_column('ai_employees', sa.Column('maturity', sa.String(length=40), nullable=True))
    op.add_column('ai_employees', sa.Column('risk_level', sa.String(length=20), nullable=True))
    op.add_column('ai_employees', sa.Column('version', sa.Integer(), nullable=True))
    op.add_column('ai_employees', sa.Column('owner_id', sa.String(length=36), nullable=True))
    op.add_column('ai_employees', sa.Column('created_by_id', sa.String(length=36), nullable=True))
    op.add_column('ai_employees', sa.Column('shadow_mode', sa.Boolean(), nullable=True))
    op.add_column('ai_employees', sa.Column('published_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ai_employees', sa.Column('certified_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('ai_employees', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.execute("UPDATE ai_employees SET code = 'emp-' || substr(id, 1, 8) WHERE code IS NULL")
    op.execute("UPDATE ai_employees SET lifecycle_status = 'ACTIVE' WHERE lifecycle_status IS NULL")
    op.execute("UPDATE ai_employees SET maturity = 'AUTONOMOUS_CONTROLLED' WHERE maturity IS NULL")
    op.execute("UPDATE ai_employees SET risk_level = 'LOW' WHERE risk_level IS NULL")
    op.execute("UPDATE ai_employees SET version = 1 WHERE version IS NULL")
    op.get_bind().execute(
        sa.text("UPDATE ai_employees SET shadow_mode = :shadow_mode WHERE shadow_mode IS NULL"),
        {"shadow_mode": False},
    )
    op.execute("UPDATE ai_employees SET updated_at = created_at WHERE updated_at IS NULL")
    with op.batch_alter_table('ai_employees') as batch_op:
        batch_op.alter_column('code', nullable=False)
        batch_op.alter_column('lifecycle_status', nullable=False)
        batch_op.alter_column('maturity', nullable=False)
        batch_op.alter_column('risk_level', nullable=False)
        batch_op.alter_column('version', nullable=False)
        batch_op.alter_column('shadow_mode', nullable=False)
        batch_op.alter_column('updated_at', nullable=False)
        batch_op.create_foreign_key('fk_ai_employees_owner', 'users', ['owner_id'], ['id'])
        batch_op.create_foreign_key('fk_ai_employees_created_by', 'users', ['created_by_id'], ['id'])
    op.create_index(op.f('ix_ai_employees_code'), 'ai_employees', ['code'], unique=False)
    op.create_index(op.f('ix_ai_employees_lifecycle_status'), 'ai_employees', ['lifecycle_status'], unique=False)
    op.create_index(op.f('ix_ai_employees_organization_id'), 'ai_employees', ['organization_id'], unique=False)
    op.add_column('capabilities', sa.Column('inputs_json', sa.Text(), nullable=True))
    op.add_column('capabilities', sa.Column('outputs_json', sa.Text(), nullable=True))
    op.add_column('capabilities', sa.Column('executor_types_json', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('capabilities', 'executor_types_json')
    op.drop_column('capabilities', 'outputs_json')
    op.drop_column('capabilities', 'inputs_json')
    op.drop_constraint(None, 'ai_employees', type_='foreignkey')
    op.drop_constraint(None, 'ai_employees', type_='foreignkey')
    op.drop_index(op.f('ix_ai_employees_organization_id'), table_name='ai_employees')
    op.drop_index(op.f('ix_ai_employees_lifecycle_status'), table_name='ai_employees')
    op.drop_index(op.f('ix_ai_employees_code'), table_name='ai_employees')
    op.drop_column('ai_employees', 'updated_at')
    op.drop_column('ai_employees', 'certified_at')
    op.drop_column('ai_employees', 'published_at')
    op.drop_column('ai_employees', 'shadow_mode')
    op.drop_column('ai_employees', 'created_by_id')
    op.drop_column('ai_employees', 'owner_id')
    op.drop_column('ai_employees', 'version')
    op.drop_column('ai_employees', 'risk_level')
    op.drop_column('ai_employees', 'maturity')
    op.drop_column('ai_employees', 'lifecycle_status')
    op.drop_column('ai_employees', 'objective')
    op.drop_column('ai_employees', 'role')
    op.drop_column('ai_employees', 'description')
    op.drop_column('ai_employees', 'code')
    op.drop_index(op.f('ix_employee_test_runs_employee_id'), table_name='employee_test_runs')
    op.drop_table('employee_test_runs')
    op.drop_index(op.f('ix_employee_versions_employee_id'), table_name='employee_versions')
    op.drop_table('employee_versions')
    op.drop_index(op.f('ix_employee_tool_grants_employee_id'), table_name='employee_tool_grants')
    op.drop_table('employee_tool_grants')
    op.drop_index(op.f('ix_employee_test_cases_employee_id'), table_name='employee_test_cases')
    op.drop_table('employee_test_cases')
    op.drop_table('employee_model_policies')
    op.drop_table('employee_limits')
    op.drop_index(op.f('ix_employee_knowledge_sources_employee_id'), table_name='employee_knowledge_sources')
    op.drop_table('employee_knowledge_sources')
    op.drop_table('employee_instructions')
    op.drop_index(op.f('ix_employee_certifications_employee_id'), table_name='employee_certifications')
    op.drop_table('employee_certifications')
    op.drop_index(op.f('ix_employee_templates_code'), table_name='employee_templates')
    op.drop_table('employee_templates')
    # ### end Alembic commands ###
