import { useEffect, useMemo, useState } from "react";
import { useParams, useSearchParams } from "react-router-dom";
import { fetchDemoSalaPublic, sendDemoGuestInterest, type DemoSala } from "../api";
import { DEMO_MEETING_TOPICS } from "../lib/demoMeetingCatalog";
import { DemoDomainVisuals } from "../components/DemoDomainVisuals";

const IMPACTS=[["↗","Ingresos"],["↘","Pérdidas"],["◉","Costos"],["⚡","Productividad"],["◇","Riesgos"]] as const;
const IMPACT_DETAIL:any={Ingresos:{value:"+ $185 M",title:"Potencial de nuevos ingresos",text:"Capacidad disponible y demanda no capturada."},"Pérdidas":{value:"$742 M",title:"Valor expuesto en cartera",text:"Cartera envejecida y devoluciones requieren intervención."},Costos:{value:"31%",title:"Concentración relevante",text:"Dependencias que pueden afectar costo y margen."},Productividad:{value:"18,7 días",title:"Oportunidad de ciclo",text:"Reducir tiempos libera capacidad operativa."},Riesgos:{value:"2 alertas",title:"Riesgos priorizados",text:"Concentración y cartera requieren seguimiento ejecutivo."}};
export function DemoGuestRoomPage(){
 const {codigo=""}=useParams(); const [sp]=useSearchParams(); const token=sp.get("token")||"";
 const [sala,setSala]=useState<DemoSala|null>(null),[error,setError]=useState<string|null>(null),[interestMsg,setInterestMsg]=useState<string|null>(null);
 const [impact,setImpact]=useState("Ingresos"),[panel,setPanel]=useState<"hallazgo"|"evidencia"|"importa"|"accion"|"avance">("hallazgo"),[focus,setFocus]=useState(0),[detailOpen,setDetailOpen]=useState(false);
 useEffect(()=>{let stop=false;const load=()=>fetchDemoSalaPublic(codigo,token).then(x=>{if(!stop){setSala(x);setError(null)}}).catch(e=>{if(!stop)setError(e.message)});load();const id=setInterval(load,1500);return()=>{stop=true;clearInterval(id)}},[codigo,token]);
 const v=sala?.visible as any; const topic=useMemo(()=>DEMO_MEETING_TOPICS.find(t=>t.id===sala?.tema)||DEMO_MEETING_TOPICS[0],[sala?.tema]); const findings=Array.isArray(v?.contenido)&&v.contenido.length?v.contenido:topic.hallazgos;
 const registrar=async(accion:string,detalle:string)=>{try{await sendDemoGuestInterest(codigo,token,accion,topic.label,detalle);setInterestMsg("✓ Interés enviado al presentador");setTimeout(()=>setInterestMsg(null),3000)}catch{setInterestMsg("No fue posible registrar el interés")}};
 if(error)return <main className="guest-room"><h1>EIIAX · Sala ejecutiva</h1><p className="error">{error}</p></main>;
 if(!sala)return <main className="guest-room"><h1>EIIAX · Sala ejecutiva</h1><p>Conectando con la reunión…</p></main>;
 const current=findings[Math.min(focus,findings.length-1)]||topic.oportunidades[0];
 const narrative=topic.narrativa[focus%topic.narrativa.length];
 const openFinding=(i:number)=>{setFocus(i);setDetailOpen(true)};
 return <main className="guest-room guest-room-v8">
  <header className="guest-executive-header">
   <div className="guest-logo-plate"><img src="/assets/identity/eiaax-logo-approved.png" alt="EIIAX"/></div>
   <div className="guest-executive-title"><span className="semantic-badge hecho">● EN VIVO · {v?.nivel||"DEMO"}</span><h1>{v?.titulo||topic.label}</h1><p>IA aplicada para convertir evidencia en decisiones con impacto.</p></div>
   <div className="guest-impact guest-impact-top">{IMPACTS.map(([i,l])=><button key={l} className={impact===l?"active":""} onClick={()=>setImpact(l)}><b>{i}</b>{l}</button>)}</div>
  </header>
  <section className="guest-decision-strip"><div><span>IMPACTO ACTIVO</span><strong>{IMPACT_DETAIL[impact].value}</strong><p>{IMPACT_DETAIL[impact].title}</p><small>{IMPACT_DETAIL[impact].text}</small></div><button onClick={()=>registrar("QUIERO_PROFUNDIZAR",IMPACT_DETAIL[impact].title)}>Quiero profundizar →</button></section>
  <nav className="guest-actionbar guest-actionbar-v8"><button className={panel==="hallazgo"?"active":""} onClick={()=>setPanel("hallazgo")}>◈ Hallazgo</button><button className={panel==="evidencia"?"active":""} onClick={()=>setPanel("evidencia")}>▥ Evidencia</button><button className={panel==="importa"?"active":""} onClick={()=>setPanel("importa")}>◎ Por qué importa</button><button className={panel==="accion"?"active":""} onClick={()=>setPanel("accion")}>✓ Qué haríamos</button><button className={panel==="avance"?"active":""} onClick={()=>setPanel("avance")}>↗ Avances</button></nav>
  <section className="guest-workspace guest-workspace-v8">
   {panel==="hallazgo"&&<div className="guest-v8-layout guest-v10-command"><article className="guest-story guest-story-v8 guest-v10-hero"><span>OPORTUNIDAD PRIORITARIA · {String(focus+1).padStart(2,"0")}</span><h2>{String(current).replace(/^Oportunidad:\s*/,"")}</h2><p>{narrative}</p><div className="guest-story-impact"><b>{IMPACT_DETAIL[impact].value}</b><small>{IMPACT_DETAIL[impact].title}</small></div><div className="guest-story-actions"><button onClick={()=>registrar("PRIORIZAR_OPORTUNIDAD",String(current))}>Me interesa esta oportunidad</button><button onClick={()=>setPanel("evidencia")}>Explorar evidencia →</button></div></article><div className="guest-v10-discovery"><header><span>RADAR DE OPORTUNIDADES</span><strong>Explore. Cada señal abre una lectura ejecutiva.</strong></header><div className="guest-opportunity-rail guest-opportunity-rail-v8 guest-v10-grid">{findings.slice(0,6).map((x:string,i:number)=><button key={i} className={focus===i?"active":""} onClick={()=>openFinding(i)}><b>{["◆","◉","▲","●","✦","⬡"][i%6]} {String(i+1).padStart(2,"0")}</b><span>{x.replace(/^Oportunidad:\s*/,"")}</span><small>{i<2?"ALTA PRIORIDAD":i<4?"OPORTUNIDAD":"EXPLORAR"}</small><em>Descubrir →</em></button>)}</div></div>{detailOpen&&<aside className="guest-v10-detail"><button className="guest-v10-close" onClick={()=>setDetailOpen(false)}>×</button><span>LECTURA EJECUTIVA</span><h3>{String(current).replace(/^Oportunidad:\s*/,"")}</h3><p>{narrative}</p><div className="guest-v10-explain"><div><b>Qué observamos</b><p>{String(current).replace(/^Oportunidad:\s*/,"")}.</p></div><div><b>Por qué importa</b><p>{IMPACT_DETAIL[impact].text}</p></div><div><b>Qué validaríamos</b><p>Magnitud, recurrencia, responsables, datos fuente y dependencia con otros procesos.</p></div><div><b>Qué decisión habilita</b><p>Priorizar la oportunidad, profundizar evidencia o llevarla a evaluación con datos reales.</p></div></div><div className="guest-v10-detail-actions"><button onClick={()=>setPanel("evidencia")}>Ver evidencia relacionada</button><button onClick={()=>registrar("PROFUNDIZAR_HALLAZGO",String(current))}>Quiero profundizar</button></div></aside>}</div>}
   {panel==="evidencia"&&<div className="guest-evidence-v8"><div className="guest-evidence-head"><div><span>EVIDENCIA DEMOSTRATIVA</span><h2>No solo mostramos un indicador: mostramos dónde actuar.</h2></div><div className="guest-kpi-strip">{topic.indicadores.slice(0,4).map((x,i)=><article key={x}><b>{["01","02","03","04"][i]}</b><span>{x}</span></article>)}</div></div><DemoDomainVisuals topic={topic}/></div>}
   {panel==="importa"&&<div className="guest-why-v9"><article><span>IMPACTO EJECUTIVO</span><h2>{IMPACT_DETAIL[impact].title}</h2><strong>{IMPACT_DETAIL[impact].value}</strong><p>{IMPACT_DETAIL[impact].text} La prioridad no se define solo por tamaño: EIIAX cruza impacto, evidencia, viabilidad y dependencia operativa antes de recomendar una intervención.</p></article><div className="guest-why-grid"><div><b>01</b><strong>Resultado</strong><p>Qué ingreso, pérdida, costo, productividad o riesgo puede cambiar.</p></div><div><b>02</b><strong>Causa y evidencia</strong><p>Qué datos sostienen la señal y dónde debe validarse.</p></div><div><b>03</b><strong>Decisión</strong><p>Qué conviene priorizar y qué información falta para decidir.</p></div><div><b>04</b><strong>Medición</strong><p>Línea base, meta y resultado realizado para demostrar el beneficio.</p></div></div></div>}
   {panel==="avance"&&<div className="guest-progress-v9"><div className="guest-progress-head"><span>SEGUIMIENTO EJECUTIVO</span><h2>De la oportunidad identificada al beneficio realizado</h2><p>Esta vista se habilita con datos reales durante la implementación. En demo muestra la estructura de seguimiento, no resultados reales.</p></div><div className="guest-progress-kpis"><article><small>Avance de implementación</small><b>—</b><span>Pendiente de contratación</span></article><article><small>Potencial identificado</small><b>{IMPACT_DETAIL[impact].value}</b><span>Estimación demostrativa</span></article><article><small>Beneficio validado</small><b>—</b><span>Requiere línea base real</span></article><article><small>Beneficio realizado</small><b>—</b><span>Se acumula con evidencia</span></article></div><div className="guest-progress-flow"><div><b>1</b><strong>Línea base</strong><span>Validar punto de partida</span></div><div><b>2</b><strong>Plan e hitos</strong><span>Responsables y fechas</span></div><div><b>3</b><strong>Resultado</strong><span>Medición periódica</span></div><div><b>4</b><strong>Beneficio</strong><span>Evidencia y acumulado</span></div></div><button onClick={()=>registrar("SEGUIMIENTO_EJECUTIVO","Interés en seguimiento periódico de implementación y beneficios")}>Quiero seguimiento ejecutivo →</button></div>}
   {panel==="accion"&&<div className="guest-action-v8"><div className="guest-action-copy"><span>CÓMO LO LLEVARÍAMOS A SU EMPRESA</span><h2>De una señal a una mejora medible, sin entregar el diagnóstico antes de validarlo.</h2><p>La demostración enseña capacidad. Con sus datos validamos magnitud, evidencia y prioridad. El detalle operativo completo se desarrolla dentro del alcance contratado.</p></div>{Array.isArray(v?.metodologia)&&<div className="guest-method-mini">{v.metodologia.map((x:string,i:number)=><span key={x}><b>{i+1}</b>{x}</span>)}</div>}<div className="guest-next-actions guest-next-actions-v7"><button onClick={()=>registrar("EVALUAR_CON_MIS_DATOS","Solicita evaluación preliminar controlada")}><b>01</b><div><strong>Evaluar con mis datos</strong><p>Cuantificar oportunidad y evidencia sin revelar aún todo el diagnóstico.</p><em>Solicitar evaluación →</em></div></button><button onClick={()=>registrar("MOSTRAR_METODOLOGIA","Solicita conocer cómo se implementaría")}><b>02</b><div><strong>¿Cómo lo implementarían?</strong><p>Mostrar metodología, alcance, responsables, tiempos e indicadores.</p><em>Ver metodología →</em></div></button><button onClick={()=>registrar("SIGUIENTE_SESION","Solicita siguiente paso comercial")}><b>03</b><div><strong>Definir siguiente paso</strong><p>Registrar el interés para preparar una propuesta enfocada.</p><em>Continuar →</em></div></button></div></div>}
   {v?.respuesta&&<div className="elia-answer guest-elia"><strong>ELIA · RESPUESTA PUBLICADA</strong><p>{v.respuesta}</p></div>}
  </section>
  {interestMsg&&<div className="guest-interest-confirm">{interestMsg}</div>}<footer className="guest-footer guest-footer-v7"><span>Demo: cifras simuladas/estimadas. Resultados reales requieren validación con datos de la entidad.</span><strong>Sala {sala.codigo} · sincronización automática</strong></footer>
 </main>
}