"""Enumeraciones — Modelo comercial basado en valor (1280)."""

from __future__ import annotations


class ValueNature:
    VERIFICADO = "VERIFICADO"
    ESTIMADO = "ESTIMADO"
    POTENCIAL = "POTENCIAL"
    ALL = frozenset({VERIFICADO, ESTIMADO, POTENCIAL})


class ValueScope:
    """Ámbito del valor — alineado con valoración 1210 e integración futura 1240."""

    INTERNO = "INTERNO"
    EXTERNO = "EXTERNO"
    ALL = frozenset({INTERNO, EXTERNO})


class ValueCategory:
    AHORRO = "AHORRO"
    PERDIDA_EVITADA = "PERDIDA_EVITADA"
    INGRESO_RECUPERADO = "INGRESO_RECUPERADO"
    PRODUCTIVIDAD_LIBERADA = "PRODUCTIVIDAD_LIBERADA"
    REDUCCION_ERRORES = "REDUCCION_ERRORES"
    REDUCCION_TIEMPOS = "REDUCCION_TIEMPOS"
    MITIGACION_RIESGO = "MITIGACION_RIESGO"
    NUEVO_INGRESO = "NUEVO_INGRESO"
    OPORTUNIDAD_CAPTURADA = "OPORTUNIDAD_CAPTURADA"
    ALL = frozenset({
        AHORRO, PERDIDA_EVITADA, INGRESO_RECUPERADO, PRODUCTIVIDAD_LIBERADA,
        REDUCCION_ERRORES, REDUCCION_TIEMPOS, MITIGACION_RIESGO, NUEVO_INGRESO,
        OPORTUNIDAD_CAPTURADA,
    })
    INTERNO = frozenset({
        AHORRO, PERDIDA_EVITADA, INGRESO_RECUPERADO, PRODUCTIVIDAD_LIBERADA,
        REDUCCION_ERRORES, REDUCCION_TIEMPOS, MITIGACION_RIESGO,
    })
    EXTERNO = frozenset({NUEVO_INGRESO, OPORTUNIDAD_CAPTURADA})


class ScenarioType:
    CONSERVADOR = "CONSERVADOR"
    BASE = "BASE"
    ALTO = "ALTO"
    ALL = frozenset({CONSERVADOR, BASE, ALTO})


class CostCategory:
    IMPLEMENTACION = "IMPLEMENTACION"
    CONFIGURACION = "CONFIGURACION"
    LICENCIAS = "LICENCIAS"
    INFRAESTRUCTURA = "INFRAESTRUCTURA"
    SOPORTE = "SOPORTE"
    OPERACION = "OPERACION"
    CONSUMO_IA = "CONSUMO_IA"
    INTEGRACIONES = "INTEGRACIONES"
    SERVICIOS_ADICIONALES = "SERVICIOS_ADICIONALES"
    ALL = frozenset({
        IMPLEMENTACION, CONFIGURACION, LICENCIAS, INFRAESTRUCTURA, SOPORTE,
        OPERACION, CONSUMO_IA, INTEGRACIONES, SERVICIOS_ADICIONALES,
    })


class CostClass:
    COSTO_PROVEEDOR_IA = "COSTO_PROVEEDOR_IA"
    COSTO_INTERNO = "COSTO_INTERNO"
    PRECIO_CLIENTE = "PRECIO_CLIENTE"
    ALL = frozenset({COSTO_PROVEEDOR_IA, COSTO_INTERNO, PRECIO_CLIENTE})


class CredentialMode:
    IA_ADMINISTRADA = "IA_ADMINISTRADA"
    CREDENCIALES_PROPIAS = "CREDENCIALES_PROPIAS"
    ALL = frozenset({IA_ADMINISTRADA, CREDENCIALES_PROPIAS})


class ProposalStatus:
    BORRADOR = "BORRADOR"
    EN_REVISION = "EN_REVISION"
    APROBADA = "APROBADA"
    RECHAZADA = "RECHAZADA"
    ENVIADA = "ENVIADA"
    ACEPTADA = "ACEPTADA"
    VENCIDA = "VENCIDA"
    ALL = frozenset({
        BORRADOR, EN_REVISION, APROBADA, RECHAZADA, ENVIADA, ACEPTADA, VENCIDA,
    })


class DoubleCountSeverity:
    ADVERTENCIA = "ADVERTENCIA"
    CRITICO = "CRITICO"
    ALL = frozenset({ADVERTENCIA, CRITICO})
