"""Enumeraciones — Continuidad operativa y resiliencia (1360)."""

from __future__ import annotations


class Criticidad:
    BAJA = "BAJA"
    MEDIA = "MEDIA"
    ALTA = "ALTA"
    CRITICA = "CRITICA"
    ALL = frozenset({BAJA, MEDIA, ALTA, CRITICA})


class EstadoPlan:
    BORRADOR = "BORRADOR"
    VIGENTE = "VIGENTE"
    EN_PRUEBA = "EN_PRUEBA"
    ACTIVADO = "ACTIVADO"
    EN_RECUPERACION = "EN_RECUPERACION"
    CERRADO = "CERRADO"
    REQUIERE_REVISION = "REQUIERE_REVISION"
    ALL = frozenset({BORRADOR, VIGENTE, EN_PRUEBA, ACTIVADO, EN_RECUPERACION, CERRADO, REQUIERE_REVISION})


class EstadoBackup:
    PROGRAMADO = "PROGRAMADO"
    EJECUTADO = "EJECUTADO"
    VERIFICADO = "VERIFICADO"
    RESTAURADO_EN_PRUEBA = "RESTAURADO_EN_PRUEBA"
    ALL = frozenset({PROGRAMADO, EJECUTADO, VERIFICADO, RESTAURADO_EN_PRUEBA})


class ResultadoBackup:
    EXITOSO = "EXITOSO"
    FALLIDO = "FALLIDO"
    PARCIAL = "PARCIAL"
    ALL = frozenset({EXITOSO, FALLIDO, PARCIAL})


class TipoRestore:
    SIMULADA = "SIMULADA"
    REAL = "REAL"
    ALL = frozenset({SIMULADA, REAL})


class SeveridadIncidente:
    SEV1 = "SEV1"
    SEV2 = "SEV2"
    SEV3 = "SEV3"
    SEV4 = "SEV4"
    ALL = frozenset({SEV1, SEV2, SEV3, SEV4})


class EstadoIncidente:
    DETECTADO = "DETECTADO"
    CONFIRMADO = "CONFIRMADO"
    EN_CONTENCION = "EN_CONTENCION"
    EN_RECUPERACION = "EN_RECUPERACION"
    MONITOREANDO = "MONITOREANDO"
    RESUELTO = "RESUELTO"
    CERRADO = "CERRADO"
    ALL = frozenset({
        DETECTADO, CONFIRMADO, EN_CONTENCION, EN_RECUPERACION,
        MONITOREANDO, RESUELTO, CERRADO,
    })


class EstadoOperacional:
    DISPONIBLE = "DISPONIBLE"
    DEGRADADO = "DEGRADADO"
    NO_DISPONIBLE = "NO_DISPONIBLE"
    DESCONOCIDO = "DESCONOCIDO"
    ALL = frozenset({DISPONIBLE, DEGRADADO, NO_DISPONIBLE, DESCONOCIDO})


class TipoPruebaContinuidad:
    SIMULACION = "SIMULACION"
    PRUEBA_TECNICA = "PRUEBA_TECNICA"
    PRUEBA_PARCIAL = "PRUEBA_PARCIAL"
    PRUEBA_COMPLETA = "PRUEBA_COMPLETA"
    ALL = frozenset({SIMULACION, PRUEBA_TECNICA, PRUEBA_PARCIAL, PRUEBA_COMPLETA})


class CausaRaiz:
    CONFIRMADA = "CONFIRMADA"
    PROBABLE = "PROBABLE"
    NO_DETERMINADA = "NO_DETERMINADA"
    ALL = frozenset({CONFIRMADA, PROBABLE, NO_DETERMINADA})
