"""Enums — Continuidad comercial y operacional EIAAX (1720)."""


class EstadoEntregable:
    PENDIENTE = "PENDIENTE"
    EN_PROGRESO = "EN_PROGRESO"
    ENTREGADO = "ENTREGADO"
    ACEPTADO = "ACEPTADO"
    RECHAZADO = "RECHAZADO"
    ALL = frozenset({PENDIENTE, EN_PROGRESO, ENTREGADO, ACEPTADO, RECHAZADO})


class AceptacionEntregable:
    PENDIENTE = "PENDIENTE"
    ACEPTADO = "ACEPTADO"
    RECHAZADO = "RECHAZADO"
    ALL = frozenset({PENDIENTE, ACEPTADO, RECHAZADO})


class EstadoCambioAlcance:
    SOLICITADO = "SOLICITADO"
    EN_ANALISIS = "EN_ANALISIS"
    IMPACTO_EVALUADO = "IMPACTO_EVALUADO"
    DECIDIDO = "DECIDIDO"
    APROBADO = "APROBADO"
    RECHAZADO = "RECHAZADO"
    IMPLEMENTANDO = "IMPLEMENTANDO"
    CERRADO = "CERRADO"
    ALL = frozenset({
        SOLICITADO, EN_ANALISIS, IMPACTO_EVALUADO, DECIDIDO,
        APROBADO, RECHAZADO, IMPLEMENTANDO, CERRADO,
    })


class EstadoCierreContrato:
    INICIADO = "INICIADO"
    EN_PROCESO = "EN_PROCESO"
    COMPLETADO = "COMPLETADO"
    ALL = frozenset({INICIADO, EN_PROCESO, COMPLETADO})
