"""Enumeraciones — Inteligencia externa y oportunidades estratégicas (1240)."""

from __future__ import annotations


class ExternalSourceType:
    MERCADO = "MERCADO"
    COMPETENCIA = "COMPETENCIA"
    CLIENTES = "CLIENTES"
    REGULACION = "REGULACIÓN"
    TECNOLOGIA = "TECNOLOGÍA"
    ECONOMIA = "ECONOMÍA"
    DEMOGRAFIA = "DEMOGRAFÍA"
    PROVEEDORES = "PROVEEDORES"
    SOCIOS_ALIADOS = "SOCIOS/ALIADOS"
    TENDENCIAS = "TENDENCIAS"
    OTRAS = "OTRAS"

    ALL = (
        MERCADO,
        COMPETENCIA,
        CLIENTES,
        REGULACION,
        TECNOLOGIA,
        ECONOMIA,
        DEMOGRAFIA,
        PROVEEDORES,
        SOCIOS_ALIADOS,
        TENDENCIAS,
        OTRAS,
    )


class IngestionChannel:
    API = "API"
    ARCHIVO = "ARCHIVO"
    MANUAL = "CARGA MANUAL"
    WEBHOOK = "WEBHOOK/EVENTO"
    INTEGRACION_FUTURA = "INTEGRACIÓN FUTURA"
    DOCUMENTAL = "FUENTE DOCUMENTAL"

    ALL = (API, ARCHIVO, MANUAL, WEBHOOK, INTEGRACION_FUTURA, DOCUMENTAL)


class SignalClassification:
    OPORTUNIDAD = "OPORTUNIDAD"
    RIESGO = "RIESGO"
    CAMBIO = "CAMBIO"
    TENDENCIA = "TENDENCIA"
    EVENTO = "EVENTO"
    INFORMACION = "INFORMACIÓN"


class RelevanceLevel:
    RELEVANTE = "RELEVANTE"
    POSIBLEMENTE_RELEVANTE = "POSIBLEMENTE RELEVANTE"
    NO_RELEVANTE = "NO RELEVANTE"


class FreshnessStatus:
    ACTUAL = "ACTUAL"
    RECIENTE = "RECIENTE"
    DESACTUALIZADA = "DESACTUALIZADA"
    SIN_FECHA = "SIN FECHA VERIFICABLE"


class ContentLayer:
    HECHO_OBSERVADO = "HECHO OBSERVADO"
    INTERPRETACION = "INTERPRETACIÓN"
    HIPOTESIS = "HIPÓTESIS"
    OPORTUNIDAD_PROPUESTA = "OPORTUNIDAD PROPUESTA"
