"""Enumeraciones — Implementación y éxito del cliente (1340)."""

from __future__ import annotations


class EstadoImplementacion:
    PLANIFICACION = "PLANIFICACION"
    PREPARACION = "PREPARACION"
    CONFIGURACION = "CONFIGURACION"
    PILOTO = "PILOTO"
    VALIDACION = "VALIDACION"
    EN_PRODUCCION = "EN_PRODUCCION"
    ESTABILIZACION = "ESTABILIZACION"
    OPERACION = "OPERACION"
    PAUSADO = "PAUSADO"
    CERRADO = "CERRADO"
    CANCELADO = "CANCELADO"
    ALL = frozenset({
        PLANIFICACION, PREPARACION, CONFIGURACION, PILOTO, VALIDACION,
        EN_PRODUCCION, ESTABILIZACION, OPERACION, PAUSADO, CERRADO, CANCELADO,
    })


class ResponsabilidadTipo:
    NUESTRO_EQUIPO = "NUESTRO_EQUIPO"
    CLIENTE = "CLIENTE"
    TERCERO = "TERCERO"
    COMPARTIDA = "COMPARTIDA"
    ALL = frozenset({NUESTRO_EQUIPO, CLIENTE, TERCERO, COMPARTIDA})


class EstadoItem:
    PENDIENTE = "PENDIENTE"
    EN_PROGRESO = "EN_PROGRESO"
    COMPLETADO = "COMPLETADO"
    BLOQUEADO = "BLOQUEADO"
    CANCELADO = "CANCELADO"
    ALL = frozenset({PENDIENTE, EN_PROGRESO, COMPLETADO, BLOQUEADO, CANCELADO})


class TipoBloqueador:
    CLIENTE = "CLIENTE"
    INTERNO = "INTERNO"
    TERCERO = "TERCERO"
    TECNICO = "TECNICO"
    DATOS = "DATOS"
    SEGURIDAD = "SEGURIDAD"
    LEGAL = "LEGAL"
    OPERATIVO = "OPERATIVO"
    OTRO = "OTRO"
    ALL = frozenset({CLIENTE, INTERNO, TERCERO, TECNICO, DATOS, SEGURIDAD, LEGAL, OPERATIVO, OTRO})


class ReadinessResultado:
    LISTO = "LISTO"
    LISTO_CON_OBSERVACIONES = "LISTO_CON_OBSERVACIONES"
    NO_LISTO = "NO_LISTO"
    ALL = frozenset({LISTO, LISTO_CON_OBSERVACIONES, NO_LISTO})


class ResultadoPiloto:
    EXITOSO = "EXITOSO"
    EXITOSO_CON_AJUSTES = "EXITOSO_CON_AJUSTES"
    NO_CONCLUYENTE = "NO_CONCLUYENTE"
    NO_EXITOSO = "NO_EXITOSO"
    ALL = frozenset({EXITOSO, EXITOSO_CON_AJUSTES, NO_CONCLUYENTE, NO_EXITOSO})


class EstadoValor:
    NO_MEDIDO = "NO_MEDIDO"
    EN_MEDICION = "EN_MEDICION"
    POR_DEBAJO = "POR_DEBAJO_DE_LO_ESPERADO"
    EN_LINEA = "EN_LINEA"
    POR_ENCIMA = "POR_ENCIMA_DE_LO_ESPERADO"
    ALL = frozenset({NO_MEDIDO, EN_MEDICION, POR_DEBAJO, EN_LINEA, POR_ENCIMA})


class SaludCliente:
    SALUDABLE = "SALUDABLE"
    ATENCION = "ATENCION"
    RIESGO = "RIESGO"
    ALL = frozenset({SALUDABLE, ATENCION, RIESGO})


class EstadoRenovacion:
    PENDIENTE = "PENDIENTE"
    EN_REVISION = "EN_REVISION"
    PROPUESTA = "PROPUESTA"
    RENOVADA = "RENOVADA"
    NO_RENOVADA = "NO_RENOVADA"
    ALL = frozenset({PENDIENTE, EN_REVISION, PROPUESTA, RENOVADA, NO_RENOVADA})


class CausaDesviacion:
    ADOPCION = "ADOPCION"
    DATOS = "DATOS"
    INTEGRACION = "INTEGRACION"
    CONFIGURACION = "CONFIGURACION"
    PROCESO_CLIENTE = "PROCESO_CLIENTE"
    SUPUESTO_INCORRECTO = "SUPUESTO_INCORRECTO"
    CONSUMO = "CONSUMO"
    CAPACIDAD = "CAPACIDAD"
    TERCERO = "TERCERO"
    OTRO = "OTRO"
    ALL = frozenset({
        ADOPCION, DATOS, INTEGRACION, CONFIGURACION, PROCESO_CLIENTE,
        SUPUESTO_INCORRECTO, CONSUMO, CAPACIDAD, TERCERO, OTRO,
    })
