"""Enumeraciones — Integraciones reales y conectores (1330)."""

from __future__ import annotations


class ConnectorType:
    API_REST = "API_REST"
    BASE_DATOS = "BASE_DATOS"
    ARCHIVO = "ARCHIVO"
    SFTP = "SFTP"
    WEBHOOK = "WEBHOOK"
    CORREO = "CORREO"
    EVENTO = "EVENTO"
    ALL = frozenset({API_REST, BASE_DATOS, ARCHIVO, SFTP, WEBHOOK, CORREO, EVENTO})


class ConnectorStatus:
    BORRADOR = "BORRADOR"
    CONFIGURANDO = "CONFIGURANDO"
    VALIDANDO = "VALIDANDO"
    ACTIVO = "ACTIVO"
    DEGRADADO = "DEGRADADO"
    ERROR = "ERROR"
    INACTIVO = "INACTIVO"
    ALL = frozenset({BORRADOR, CONFIGURANDO, VALIDANDO, ACTIVO, DEGRADADO, ERROR, INACTIVO})


class AuthType:
    NINGUNA = "NINGUNA"
    API_KEY = "API_KEY"
    BEARER = "BEARER"
    BASIC = "BASIC"
    OAUTH2 = "OAUTH2"
    ALL = frozenset({NINGUNA, API_KEY, BEARER, BASIC, OAUTH2})


class ExecutionStatus:
    PENDIENTE = "PENDIENTE"
    EN_PROGRESO = "EN_PROGRESO"
    EXITOSA = "EXITOSA"
    FALLIDA = "FALLIDA"
    PARCIAL = "PARCIAL"
    CANCELADA = "CANCELADA"
    ALL = frozenset({PENDIENTE, EN_PROGRESO, EXITOSA, FALLIDA, PARCIAL, CANCELADA})


class TestResult:
    EXITOSA = "EXITOSA"
    FALLIDA = "FALLIDA"
    DEGRADADA = "DEGRADADA"
    ALL = frozenset({EXITOSA, FALLIDA, DEGRADADA})


class ErrorCategory:
    CONFIGURACION = "CONFIGURACION"
    AUTENTICACION = "AUTENTICACION"
    CONEXION = "CONEXION"
    TIMEOUT = "TIMEOUT"
    VALIDACION = "VALIDACION"
    PERMISOS = "PERMISOS"
    SERVICIO_EXTERNO = "SERVICIO_EXTERNO"
    LIMITE = "LIMITE"
    SSRF = "SSRF"
    DESCONOCIDO = "DESCONOCIDO"
    ALL = frozenset({
        CONFIGURACION, AUTENTICACION, CONEXION, TIMEOUT, VALIDACION,
        PERMISOS, SERVICIO_EXTERNO, LIMITE, SSRF, DESCONOCIDO,
    })


class TriggerMode:
    MANUAL = "MANUAL"
    PROGRAMADA = "PROGRAMADA"
    EVENTO = "EVENTO"
    ALL = frozenset({MANUAL, PROGRAMADA, EVENTO})


class DestinationType:
    SENALES = "SENALES"
    CONOCIMIENTO = "CONOCIMIENTO"
    AUTOMATIZACIONES = "AUTOMATIZACIONES"
    EMPLEADOS_IA = "EMPLEADOS_IA"
    PROCESOS = "PROCESOS"
    ALL = frozenset({SENALES, CONOCIMIENTO, AUTOMATIZACIONES, EMPLEADOS_IA, PROCESOS})
