"""Enumeraciones — Segmentación y planes verticales (1310)."""

from __future__ import annotations


class CatalogLifecycle:
    BORRADOR = "BORRADOR"
    ACTIVO = "ACTIVO"
    INACTIVO = "INACTIVO"
    RETIRADO = "RETIRADO"
    ALL = frozenset({BORRADOR, ACTIVO, INACTIVO, RETIRADO})


class CapabilityCode:
    AUTOMATIZACIONES = "AUTOMATIZACIONES"
    CONOCIMIENTO = "CONOCIMIENTO"
    ANALISIS = "ANALISIS"
    OPORTUNIDADES = "OPORTUNIDADES"
    INTELIGENCIA_EXTERNA = "INTELIGENCIA_EXTERNA"
    OPTIMIZACION = "OPTIMIZACION"
    AUDITORIA = "AUDITORIA"
    INTEGRACIONES = "INTEGRACIONES"
    PROVEEDORES_IA = "PROVEEDORES_IA"
    SOPORTE_AVANZADO = "SOPORTE_AVANZADO"
    ALL = frozenset({
        AUTOMATIZACIONES, CONOCIMIENTO, ANALISIS, OPORTUNIDADES, INTELIGENCIA_EXTERNA,
        OPTIMIZACION, AUDITORIA, INTEGRACIONES, PROVEEDORES_IA, SOPORTE_AVANZADO,
    })


class DiscountType:
    PORCENTAJE = "PORCENTAJE"
    FIJO = "FIJO"
    TEMPORAL = "TEMPORAL"
    VOLUMEN = "VOLUMEN"
    ALL = frozenset({PORCENTAJE, FIJO, TEMPORAL, VOLUMEN})


class PlanFitLevel:
    INSUFICIENTE = "INSUFICIENTE"
    ADECUADO = "ADECUADO"
    EXCESIVO = "EXCESIVO"
    ALL = frozenset({INSUFICIENTE, ADECUADO, EXCESIVO})


class ScaleDirection:
    SUBIR = "SUBIR"
    BAJAR = "BAJAR"
    MANTENER = "MANTENER"
    ALL = frozenset({SUBIR, BAJAR, MANTENER})
