"""Enumeraciones — TCO y ecosistema de aliados (1320)."""

from __future__ import annotations


class TipoCosto:
    FIJO = "FIJO"
    VARIABLE = "VARIABLE"
    UNICO = "UNICO"
    ALL = frozenset({FIJO, VARIABLE, UNICO})


class NaturalezaCosto:
    ESTIMADO = "ESTIMADO"
    REAL = "REAL"
    PROYECTADO = "PROYECTADO"
    ALL = frozenset({ESTIMADO, REAL, PROYECTADO})


class Periodicidad:
    MENSUAL = "MENSUAL"
    TRIMESTRAL = "TRIMESTRAL"
    ANUAL = "ANUAL"
    POR_USO = "POR_USO"
    POR_EVENTO = "POR_EVENTO"
    POR_USUARIO = "POR_USUARIO"
    POR_EMPLEADO_IA = "POR_EMPLEADO_IA"
    POR_INTEGRACION = "POR_INTEGRACION"
    POR_UNIDAD = "POR_UNIDAD"
    ALL = frozenset({
        MENSUAL, TRIMESTRAL, ANUAL, POR_USO, POR_EVENTO,
        POR_USUARIO, POR_EMPLEADO_IA, POR_INTEGRACION, POR_UNIDAD,
    })


class CategoriaCostoDefault:
    IA = "IA"
    INFRAESTRUCTURA = "INFRAESTRUCTURA"
    INTEGRACION = "INTEGRACION"
    SOPORTE = "SOPORTE"
    SOFTWARE = "SOFTWARE"
    PERSONAL = "PERSONAL"
    ALMACENAMIENTO = "ALMACENAMIENTO"
    COMUNICACIONES = "COMUNICACIONES"
    SERVICIO_EXTERNO = "SERVICIO_EXTERNO"
    IMPLEMENTACION = "IMPLEMENTACION"
    OTROS = "OTROS"
    ALL = frozenset({
        IA, INFRAESTRUCTURA, INTEGRACION, SOPORTE, SOFTWARE, PERSONAL,
        ALMACENAMIENTO, COMUNICACIONES, SERVICIO_EXTERNO, IMPLEMENTACION, OTROS,
    })


class TipoProveedorAliado:
    PROVEEDOR_IA = "PROVEEDOR_IA"
    PROVEEDOR_INFRAESTRUCTURA = "PROVEEDOR_INFRAESTRUCTURA"
    PROVEEDOR_SOFTWARE = "PROVEEDOR_SOFTWARE"
    ALIADO_TECNOLOGICO = "ALIADO_TECNOLOGICO"
    ALIADO_IMPLEMENTACION = "ALIADO_IMPLEMENTACION"
    CONSULTOR = "CONSULTOR"
    INTEGRADOR = "INTEGRADOR"
    CANAL_COMERCIAL = "CANAL_COMERCIAL"
    SOPORTE = "SOPORTE"
    OTRO = "OTRO"
    ALL = frozenset({
        PROVEEDOR_IA, PROVEEDOR_INFRAESTRUCTURA, PROVEEDOR_SOFTWARE,
        ALIADO_TECNOLOGICO, ALIADO_IMPLEMENTACION, CONSULTOR, INTEGRADOR,
        CANAL_COMERCIAL, SOPORTE, OTRO,
    })


class MetodoDistribucion:
    PORCENTAJE_FIJO = "PORCENTAJE_FIJO"
    USO_REAL = "USO_REAL"
    USUARIOS = "USUARIOS"
    CONSUMO_IA = "CONSUMO_IA"
    TRANSACCIONES = "TRANSACCIONES"
    MANUAL = "MANUAL"
    ALL = frozenset({
        PORCENTAJE_FIJO, USO_REAL, USUARIOS, CONSUMO_IA, TRANSACCIONES, MANUAL,
    })


class TipoTarifa:
    UNIDAD = "UNIDAD"
    USO = "USO"
    VOLUMEN = "VOLUMEN"
    MENSUALIDAD = "MENSUALIDAD"
    LICENCIA = "LICENCIA"
    SERVICIO = "SERVICIO"
    ALL = frozenset({UNIDAD, USO, VOLUMEN, MENSUALIDAD, LICENCIA, SERVICIO})


class RiesgoProveedor:
    BAJO = "BAJO"
    MEDIO = "MEDIO"
    ALTO = "ALTO"
    ALL = frozenset({BAJO, MEDIO, ALTO})


class TipoAlianza:
    TECNOLOGICA = "TECNOLOGICA"
    COMERCIAL = "COMERCIAL"
    IMPLEMENTACION = "IMPLEMENTACION"
    INTEGRACION = "INTEGRACION"
    CONSULTORIA = "CONSULTORIA"
    ALL = frozenset({TECNOLOGICA, COMERCIAL, IMPLEMENTACION, INTEGRACION, CONSULTORIA})


class EstadoAlianza:
    PROPUESTA = "PROPUESTA"
    ACTIVA = "ACTIVA"
    SUSPENDIDA = "SUSPENDIDA"
    FINALIZADA = "FINALIZADA"
    ALL = frozenset({PROPUESTA, ACTIVA, SUSPENDIDA, FINALIZADA})


class TipoSimulacion:
    CAMBIO_PROVEEDOR = "CAMBIO_PROVEEDOR"
    CAMBIO_TARIFA = "CAMBIO_TARIFA"
    AUMENTO_CONSUMO = "AUMENTO_CONSUMO"
    CRECIMIENTO_USUARIOS = "CRECIMIENTO_USUARIOS"
    MAYOR_INFRAESTRUCTURA = "MAYOR_INFRAESTRUCTURA"
    CAMBIO_MONEDA = "CAMBIO_MONEDA"
    AUMENTO_SOPORTE = "AUMENTO_SOPORTE"
    MAKE_OR_BUY = "MAKE_OR_BUY"
    SUSTITUCION_PROVEEDOR = "SUSTITUCION_PROVEEDOR"
    ALL = frozenset({
        CAMBIO_PROVEEDOR, CAMBIO_TARIFA, AUMENTO_CONSUMO, CRECIMIENTO_USUARIOS,
        MAYOR_INFRAESTRUCTURA, CAMBIO_MONEDA, AUMENTO_SOPORTE, MAKE_OR_BUY,
        SUSTITUCION_PROVEEDOR,
    })


class TipoAlertaEconomica:
    TCO_EXCEDIDO = "TCO_EXCEDIDO"
    MARGEN_BAJO = "MARGEN_BAJO"
    PROVEEDOR_CARO = "PROVEEDOR_CARO"
    CONCENTRACION_ALTA = "CONCENTRACION_ALTA"
    TARIFA_POR_VENCER = "TARIFA_POR_VENCER"
    CONTRATO_POR_VENCER = "CONTRATO_POR_VENCER"
    DESVIACION_COSTO = "DESVIACION_COSTO"
    ALL = frozenset({
        TCO_EXCEDIDO, MARGEN_BAJO, PROVEEDOR_CARO, CONCENTRACION_ALTA,
        TARIFA_POR_VENCER, CONTRATO_POR_VENCER, DESVIACION_COSTO,
    })


class EstadoContrato:
    BORRADOR = "BORRADOR"
    VIGENTE = "VIGENTE"
    VENCIDO = "VENCIDO"
    SUSPENDIDO = "SUSPENDIDO"
    ALL = frozenset({BORRADOR, VIGENTE, VENCIDO, SUSPENDIDO})
