export type DemoPrivateMetricGuide={
 source:string;period:string;formula:string;records:string;filters:string;
 quality:string;strategy:string[];answer:string;realData:string[];
};
const DEFAULT:DemoPrivateMetricGuide={
 source:"Paquete demostrativo del tema activo",period:"Escenario demostrativo",formula:"Regla específica a validar con datos reales",records:"Registros ficticios del paquete",filters:"Área, período y dimensión del indicador",quality:"SIMULADO · no verificado contra una IPS real",
 strategy:["Validar línea base y calidad del dato.","Segmentar el indicador hasta identificar causas y responsables.","Priorizar intervención por impacto, factibilidad y tiempo.","Medir resultado real contra línea base y compromisos."],
 answer:"En la demo mostramos el potencial y el método de validación. En la IPS confirmaríamos primero la línea base y solo después comprometeríamos una meta medible.",
 realData:["Fuente transaccional real","Período comparable","Responsables y reglas del proceso","Evidencia de ejecución y resultado"]
};
const topic:Record<string,Partial<DemoPrivateMetricGuide>>={
 facturacion:{source:"Facturas, cartera, radicación y producción demo",formula:"Valores/saldos por estado, antigüedad, pagador y servicio",strategy:["Separar ingreso no capturado, cartera y capacidad disponible.","Bajar por pagador, servicio, edad y etapa del ciclo.","Priorizar fugas recuperables y capacidad comercial utilizable.","Medir recaudo/nuevo ingreso real sin mezclar categorías."],answer:"La captura se plantea por dos vías separadas: cerrar fugas del ciclo y utilizar capacidad con demanda/contratación comprobada. No sumamos ambos conceptos como si fueran el mismo beneficio."},
 glosas:{source:"Glosas, devoluciones, respuestas y pagos demo",formula:"Valor × recuperabilidad estimada, segmentado por causal/pagador/edad",strategy:["Separar frecuencia de impacto económico.","Clasificar causal, pagador, antigüedad y soporte disponible.","Priorizar por valor, probabilidad de recuperación y vencimiento.","Asignar acciones y medir recuperación efectivamente pagada."],answer:"El valor recuperable no se presume: se segmenta por causal, evidencia, pagador y vencimiento; la meta final se valida con expedientes reales y se mide sobre dinero efectivamente recuperado."},
 rrhh:{source:"Carga, tareas, tiempos y turnos demo",formula:"Tiempo improductivo/reproceso × frecuencia; capacidad liberable por actividad",strategy:["Medir carga y tiempo por actividad/rol.","Separar espera, reproceso y redigitación.","Automatizar o rediseñar solo tareas elegibles.","Definir uso productivo de las horas liberadas y medirlo."],answer:"Liberar horas no significa reducir personal. El valor aparece cuando esa capacidad se reasigna a actividades medibles de mayor valor y se comprueba el cambio."},
 operaciones:{source:"Eventos y etapas de proceso demo",formula:"Tiempo entre etapas + esperas + retornos/reprocesos",strategy:["Reconstruir el flujo extremo a extremo.","Medir ciclo, espera, retornos y transferencias.","Atacar cuellos de botella y reglas no estandarizadas.","Comparar ciclo y capacidad antes/después."],answer:"No analizamos solo reprocesos: medimos flujo completo, tiempos, esperas, capacidad, dependencias y cuellos de botella para localizar dónde se pierde tiempo o valor."},
 compras:{source:"Órdenes, proveedores, precios, consumo e inventario demo",formula:"Brechas de precio/consumo + inventario en riesgo, sin asumir ahorro automático",strategy:["Normalizar insumos, proveedores y condiciones comparables.","Separar variación justificable de oportunidad negociable.","Cruzar consumo, rotación, vencimiento y nivel de servicio.","Medir ahorro realizado y capital efectivamente liberado."],answer:"Una diferencia de precio no es ahorro automático. Primero se hace comparable por especificación, volumen, calidad y contrato; luego se negocia y se mide el resultado realmente obtenido."},
 sistemas:{source:"Inventario TI, interfaces, incidentes y controles demo",formula:"Exposición de riesgo + dependencia manual + cobertura de controles",strategy:["Inventariar aplicaciones, interfaces y puntos únicos de falla.","Cuantificar trabajo manual, incidentes y exposición.","Priorizar continuidad, ciberseguridad, datos e integración.","Medir reducción de riesgo, horas manuales y costo evitado por separado."],answer:"El valor tecnológico se sustenta separando continuidad, riesgo, costo y automatización; no convertimos riesgo en pesos sin una base verificable."}
};
const metricOverrides:Record<string,Partial<DemoPrivateMetricGuide>>={
 "glosas|Recuperación potencial":{formula:"Valor objetado × probabilidad de recuperación × vigencia",records:"Glosas/devoluciones ficticias con causal, valor, edad y soporte",filters:"Pagador, causal, servicio, antigüedad, soporte",quality:"POTENCIAL SIMULADO · requiere expediente real",strategy:["Identificar universo recuperable y excluir aceptaciones definitivas/no viables.","Puntuar soporte, causal, pagador, antigüedad y vencimiento.","Ordenar por valor esperado y fecha límite.","Ejecutar respuesta/cobro y medir únicamente pago recuperado."],answer:"Los $286 M son un escenario potencial, no una promesa. Para convertirlo en meta revisamos cada grupo de glosas, evidencia, probabilidad y vencimiento; el resultado se mide sobre recuperación real."},
 "facturacion|Oportunidad comercial":{formula:"Capacidad disponible utilizable × demanda validada × tarifa/margen aplicable",quality:"POTENCIAL SIMULADO · no es ingreso contratado",strategy:["Confirmar capacidad realmente disponible.","Validar demanda y restricciones operativas.","Confirmar contrato/tarifa y margen.","Medir producción y facturación incremental atribuible."],answer:"Los $185 M representan un escenario de nuevo ingreso; solo se convierte en meta después de validar capacidad, demanda, contratación y margen."},
 "rrhh|Oportunidad de capacidad":{formula:"Minutos liberables por tarea × frecuencia mensual",quality:"POTENCIAL SIMULADO · requiere estudio de tiempos",answer:"Las horas liberables se validan con tiempos y frecuencias reales y deben tener un uso productivo definido; por sí solas no equivalen a ahorro en nómina."},
 "compras|Inventario y capital inmovilizado":{formula:"Stock excedente/baja rotación × costo unitario, ajustado por consumo esperado",quality:"POTENCIAL SIMULADO · requiere kardex y política de inventario",answer:"El inventario identificado no se trata automáticamente como ahorro: se valida consumo, vencimiento, criticidad y posibilidad real de reducir o reutilizar stock."},
 "sistemas|Horas de trabajo manual":{formula:"Tiempo manual por interfaz/tarea × frecuencia mensual",quality:"POTENCIAL SIMULADO · requiere medición operativa",answer:"Las horas manuales sirven para priorizar integración; el beneficio se reconoce cuando la automatización funciona y la capacidad liberada tiene uso comprobable."}
};
const byTitle=(title:string):Partial<DemoPrivateMetricGuide>=>{
 const t=title.toLowerCase();
 if(t.includes("cartera")||t.includes("90 días"))return {formula:"Saldo pendiente segmentado por antigüedad, pagador y recuperabilidad",filters:"Pagador, edad, estado, valor",strategy:["Separar cartera corriente y vencida.","Validar disputa, soporte y gestión previa.","Priorizar valor × recuperabilidad × vencimiento.","Medir recaudo efectivo y tiempo de recuperación."]};
 if(t.includes("no facturado")||t.includes("no radicado")||t.includes("devuelto"))return {formula:"Valor/volumen detenido en la etapa seleccionada ÷ universo del ciclo",strategy:["Identificar casos detenidos y su antigüedad.","Clasificar causa y responsable.","Resolver causas recurrentes y alertar vencimientos.","Medir reducción de fuga y tiempo de ciclo."]};
 if(t.includes("soportes")||t.includes("autorización")||t.includes("tarifa")||t.includes("pertinencia"))return {formula:"Frecuencia o valor de la causal seleccionada ÷ total de glosas",filters:"Causal, pagador, servicio, valor, edad",strategy:["Bajar a casos de la causal.","Separar error prevenible de controversia válida.","Corregir origen y gestionar recuperables.","Medir reincidencia y recuperación real."]};
 if(t.includes("facturación")||t.includes("admisiones")||t.includes("dependencia manual")||t.includes("automatizables"))return {formula:"Carga observada o tiempo manual ÷ capacidad disponible",strategy:["Medir volumen y tiempo por tarea.","Localizar sobrecarga, espera y reproceso.","Redistribuir o automatizar donde sea viable.","Verificar uso productivo de capacidad liberada."]};
 if(t.includes("datos/soportes")||t.includes("transferencia manual")||t.includes("reglas no estandarizadas"))return {formula:"Casos asociados a la causa seleccionada ÷ casos con error/reproceso",strategy:["Trazar el error hasta su etapa de origen.","Definir control preventivo y responsable.","Reducir transferencias y reglas ambiguas.","Medir reincidencia y tiempo evitado."]};
 if(t.includes("medicamentos")||t.includes("dispositivos")||t.includes("proveedor")||t.includes("contrato")||t.includes("stock"))return {formula:"Participación/brecha de la dimensión seleccionada sobre gasto o abastecimiento",strategy:["Normalizar producto, proveedor y condición contractual.","Comparar precio, consumo y nivel de servicio.","Validar oportunidad negociable o riesgo de stock.","Medir ahorro/capital liberado realizado."]};
 if(t.includes("exposición")||t.includes("cobertura controles"))return {formula:"Riesgo inherente/residual y controles efectivos del escenario demo",strategy:["Identificar activo/proceso expuesto.","Validar probabilidad, impacto y controles existentes.","Priorizar mitigación por criticidad.","Medir riesgo residual y evidencia de control."]};
 return {};
};
export function getDemoPrivateMetricGuide(topicId:string,title?:string):DemoPrivateMetricGuide{
 const base={...DEFAULT,...(topic[topicId]||{})};
 const inferred=title?byTitle(title):{};
 const specific=title?metricOverrides[`${topicId}|${title}`]:undefined;
 return {...base,...inferred,...(specific||{})};
}
